=== mesouak-salaheddin/Voyageur_Sante/CABINET_MESOUAK_EL-BOUCHRIFI/src/data/xsd/cabinet.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cab="http://www.ujf-grenoble.fr/l3miage/medical"
           xmlns:pat="http://www.ujf-grenoble.fr/l3miage/medical/patient"
           targetNamespace="http://www.ujf-grenoble.fr/l3miage/medical"
           elementFormDefault="qualified">
    <xs:import schemaLocation="patient.xsd" namespace="http://www.ujf-grenoble.fr/l3miage/medical/patient"/>
    
    <!-- Racine : Cabinet -->
    <xs:element name="cabinet" type="cab:Cabinet">
        <xs:keyref name="idExist" refer="cab:infIdUnique">
            <xs:selector xpath="cab:patients/cab:patient/pat:visite"/>
            <xs:field xpath="@intervenant"/>
        </xs:keyref>
    </xs:element>
    
    
    <!-- TYPE complexe: Cabinet --> 
    <xs:complexType name="Cabinet">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="adresse" type ="cab:Adresse"/>
            <xs:element name="infirmiers" type ="cab:Infirmiers">
                <xs:unique name = "infIdUnique">
                    <xs:selector xpath="cab:infirmier" />
                    <xs:field xpath="@id"/>
                </xs:unique>
            </xs:element>
            <xs:element name="patients" type ="cab:Patients"/>
        </xs:sequence>
    </xs:complexType>
        
        
    <!-- Type complexe: Adresse -->
    <xs:complexType  name="Adresse">
        <xs:sequence> 
            <xs:element name="numéro" type="xs:string" minOccurs="0"/>
            <xs:element name="rue" type="xs:string"/>
            <xs:element name="codePostal" type="cab:CodePostal"/>
            <xs:element name="ville" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
   
   <!-- Type complexe: Code postal -->
   <xs:simpleType name="CodePostal">
        <xs:restriction base="xs:int">
            <xs:pattern value="[0-9]{5}" /> <!-- le code postal est exactement à 5 chiffres -->
        </xs:restriction>
    </xs:simpleType>
             
    <!-- Type complexe: Infirmiers --> 
    <xs:complexType  name="Infirmiers">
        <xs:sequence>
            <xs:element name="infirmier" type="cab:Infirmier" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType> 
        
        
    <!-- Type complexe: Infirmier--> 
    <xs:complexType name="Infirmier">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type="xs:string"/>
            <xs:element name="photo" type="xs:string"/>          
        </xs:sequence>  
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>   
        
        
    <!-- Type complexe: Patients-->       
    <xs:complexType name="Patients">
        <xs:sequence>
            <xs:element name="patient" type="pat:Patient" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>   
        
        
    <!-- Type complexe: Patient-->                                   
    <xs:complexType  name="Patient">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prénom" type="xs:string"/>
            <xs:element name="sexe" type="xs:string"/>
            <xs:element name="naissance" type="xs:date"/>
            <xs:element name="numéro" type="xs:string"/>
            <xs:element name="adresse" type="cab:Adresse"/>
            <xs:element name="visite" type="cab:Visite"/>
        </xs:sequence>   
    </xs:complexType>
        
           
    <!-- Type complexe: Visite -->   
    <xs:complexType name="Visite" >
        <xs:sequence>
            <xs:element name="acte" type="pat:Acte" maxOccurs="unbounded"/> 
        </xs:sequence>
        <xs:attribute name="date" type="xs:date"/>
        <xs:attribute name="intervenant" type="xs:string" use="optional"/>
    </xs:complexType>
    
       
    <!-- Type complexe:Acte --> 
    <xs:complexType name="Acte">
        <xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
   
</xs:schema>

=== mesouak-salaheddin/Voyageur_Sante/CABINET_MESOUAK_EL-BOUCHRIFI/src/data/xml/cabinet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XMLDocument.xml to edit this template
-->


<!-- Racine : Cabinet -->
<cab:cabinet
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:cab='http://www.ujf-grenoble.fr/l3miage/medical'
    xmlns:pat='http://www.ujf-grenoble.fr/l3miage/medical/patient'
    xsi:schemaLocation='http://www.ujf-grenoble.fr/l3miage/medical ../xsd/cabinet.xsd
   http://www.ujf-grenoble.fr/l3miage/medical/patient ../xsd/patient.xsd'>
    
    <!--Nom de Cabinet-->
    <cab:nom>Soins à Grenoble</cab:nom>
    
    <!--Adresse de Cabinet-->
    <cab:adresse>
        <cab:numéro>60</cab:numéro>
        <cab:rue>rue de la Chimie</cab:rue>
        <cab:codePostal>38041</cab:codePostal>
        <cab:ville>Grenoble</cab:ville>
    </cab:adresse>
    
    <!--Liste des Infirmiers-->
    <cab:infirmiers>
        
        <!--Infirmier 001-->
        <cab:infirmier id="001">
            <cab:nom>Fréchie</cab:nom>
            <cab:prénom>Sarah</cab:prénom>
            <cab:photo>sarah.png</cab:photo>
        </cab:infirmier>
        
        <!--Infirmier 002-->
        <cab:infirmier id="002">
            <cab:nom>Stické</cab:nom>
            <cab:prénom>Sophie</cab:prénom>
            <cab:photo>sophie.jpg</cab:photo>
        </cab:infirmier>
        
        <!--Infirmier 003-->
        <cab:infirmier id="003">
            <cab:nom>Ochon</cab:nom>
            <cab:prénom>Paul</cab:prénom>
            <cab:photo>paul.png</cab:photo>
        </cab:infirmier>
        
    </cab:infirmiers>
    
    <!--Liste des Patiens-->
    <cab:patients>
                
        <cab:patient>
            <!-- Homme, né en août 98 en France,
            à Marseille (n°55 en bouche du rhône)
                458e naissance
                        -->
            <pat:nom>Alécole</pat:nom>
            <pat:prénom>Yvon</pat:prénom>
            <pat:sexe>M</pat:sexe>
            <pat:naissance>1998-08-22</pat:naissance>
            <pat:numéro>198082205545852</pat:numéro>
            <pat:adresse>
                <pat:étage>6</pat:étage>
                <pat:numéro>50</pat:numéro>
                <pat:rue>avenue Félix Viallet</pat:rue>
                <pat:ville>Grenoble</pat:ville>
                <pat:codePostal>38031</pat:codePostal>
            </pat:adresse>
            <pat:visite date="2015-12-08" intervenant="001">
                <pat:acte id="109"></pat:acte>
            </pat:visite>
        </cab:patient>
               
        <cab:patient>
            <!-- Femme née le 08 mars 82 en France, 
                à Lyon (n° 23 dans le rhône),
                        52e naissance 
                            --> 
            <pat:nom>Orouge</pat:nom>
            <pat:prénom>Elvire</pat:prénom>
            <pat:sexe>F</pat:sexe>
            <pat:naissance>1982-03-08</pat:naissance>
            <pat:numéro>282036902305218</pat:numéro>
            <pat:adresse>
                <pat:rue>Rond-Point de la Croix de Vie</pat:rue>
                <pat:ville>La Tronche</pat:ville>
                <pat:codePostal>38700</pat:codePostal>
            </pat:adresse>
            <pat:visite date="2015-12-08">
                <pat:acte id="300"></pat:acte>
            </pat:visite>
        </cab:patient>
        
        <cab:patient>
            <!-- Femme née le 25 mars 75 en France, 
                à Chambery (n° 65 dans la Savoie),
                        692e naissance 
                            -->
            <pat:nom>Pien</pat:nom>
            <pat:prénom>Oscare</pat:prénom>
            <pat:sexe>F</pat:sexe>
            <pat:naissance>1975-03-25</pat:naissance>
            <pat:numéro>275037306569296</pat:numéro>
            <pat:adresse>
                <pat:rue>rue Casimir Brenier</pat:rue>
                <pat:ville>Grenoble</pat:ville>
                <pat:codePostal>38000</pat:codePostal>
            </pat:adresse>
            <pat:visite date="2015-12-08">
                <pat:acte id="101"></pat:acte>
                <pat:acte id="104"></pat:acte>
            </pat:visite>
        </cab:patient>
        
        <cab:patient>
            <!-- Petit garçon né le 02 aout 2011 en France, 
                à Bordeaux (n° 63 dans la Gironde),
                        35e naissance 
                            -->
            <pat:nom>Kapoëtla</pat:nom>
            <pat:prénom>Xavier</pat:prénom>
            <pat:sexe>M</pat:sexe>
            <pat:naissance>2011-08-02</pat:naissance>
            <pat:numéro>111083306303521</pat:numéro>
            <pat:adresse>
                <pat:numéro>25</pat:numéro>
                <pat:rue>rue Rue de Martyrs</pat:rue>
                <pat:ville>Grenoble</pat:ville>
                <pat:codePostal>38042</pat:codePostal>
            </pat:adresse>
            <pat:visite date="2015-12-08">
                <pat:acte id="111"></pat:acte>
            </pat:visite>
        </cab:patient>
        
    </cab:patients>

</cab:cabinet>
